### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by robert9422** [glennguy/plugin.video.9now#4]
I get 404 error when I try to go to the link
 https://github.com/vdrtuxnet/kodi-17.binary.addons
Rob

**Comment by glennguy** [comment]
Hi @robert9422,

Looks like they renamed the repo. It's here now:
https://github.com/vdrtuxnet/binary-repo

I'd recommend installing the appropriate repository zip file then install
inputstream. adaptive from that, that way you'll get any updates.

I'll update my readme later today, thanks for pointing this out!

On 18 May 2017 08:08, "robert9422" <notifications@github.com> wrote:

I get 404 error when I try to go to the link
https://github.com/vdrtuxnet/kodi-17.binary.addons
Rob

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/glennguy/plugin.video.9now/issues/4>, or mute the thread

**Comment by robert9422** [comment]
Hi, thanks for that, I'm very new to all this and trying to learn as I go.
Regards,
Rob.
